# Generated by Django 5.1.3 on 2024-11-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_despesa_categoria_alter_despesa_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
