# Generated by Django 5.1.3 on 2024-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='valor_gasto',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Lazer', 'Lazer'), ('Saúde', 'Saúde'), ('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ano',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='categoria',
            field=models.CharField(choices=[('Lazer', 'Lazer'), ('Saúde', 'Saúde'), ('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mes',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
