# Generated by Django 5.1.3 on 2024-12-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reserva_valor_gasto_alter_despesa_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='ano',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
