# Generated by Django 5.1.3 on 2024-12-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_despesa_ano_despesa_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='mes',
        ),
    ]
